"use client";
// import type { Metadata } from "next";
import { useState } from "react";
// export const metadata: Metadata = {
//   title: "manga wibu",
//   description: "Generated by create next app",
// };
import { Roboto } from "next/font/google";
import "@fortawesome/fontawesome-svg-core/styles.css";
import "../../styles/global.css";
import Navbar from "../../components/Navbar/Navbar";
import Footer from "../../components/Footer/Footer";
import Login from "../../components/Auth/Login";
import Register from "../../components/Auth/Register";
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400"],
  style: ["normal"],
});
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [showModalLogin, setShowModalLogin] = useState(false);
  const [showModalRegister, setShowModalRegister] = useState(false);
  return (
    <html lang="en">
      <body
        className={`${showModalLogin || showModalRegister ? "showForm" : ""} ${
          roboto.className
        }`}
      >
        {showModalLogin ? (
          <Login
            showModalLogin={showModalLogin}
            setShowModalLogin={setShowModalLogin}
            showModalRegister={showModalRegister}
            setShowModalRegister={setShowModalRegister}
          />
        ) : (
          ""
        )}
        {showModalRegister ? (
          <Register
            showModalRegister={showModalRegister}
            setShowModalRegister={setShowModalRegister}
            showModalLogin={showModalLogin}
            setShowModalLogin={setShowModalLogin}
          />
        ) : (
          ""
        )}
        <Navbar
          showModalLogin={showModalLogin}
          setShowModalLogin={setShowModalLogin}
        />
        <main className="main">{children}</main>
        {/* <Footer/> */}
      </body>
    </html>
  );
}
